Rearranged speakers
codezoned/codezoned.github.io pull request #56
Opened 2020-07-20 16:39 UTC by swaaz

![image](https://user-images.githubusercontent.com/42874695/87962456-db56d580-cad4-11ea-9970-6741dbf79131.png)
![image](https://user-images.githubusercontent.com/42874695/87962976-a7c87b00-cad5-11ea-81cd-64da064e9d69.png)

2020-07-20 20:36 UTC, swaaz commented
@ionicc 
![image](https://user-images.githubusercontent.com/42874695/87983966-d99e0980-caf6-11ea-97cd-ad65fac92c46.png)

2020-07-21 05:03 UTC, ionicc requested changes
![Screenshot (174)](https://user-images.githubusercontent.com/19570480/88014789-623f9880-cb3d-11ea-9f35-37eb3d4c7278.png)

2020-07-21 08:44 UTC, swaaz commented
Sorry I by mistake deleted one div and now I fixed it
![image](https://user-images.githubusercontent.com/42874695/88032991-6333f280-cb5c-11ea-993a-27fccadc0c0b.png)

2020-07-21 08:55 UTC, ionicc approved these changes

2020-07-21 08:55 UTC, merged