Swaaz branch
codezoned/codezoned.github.io pull request #59
Opened 2020-07-28 07:04 UTC by swaaz

2020-07-28 07:26 UTC, ionicc requested changes
![Screenshot (176)](https://user-images.githubusercontent.com/19570480/88632793-b7e1eb00-d0d1-11ea-93ac-f0f0681fdc96.png)

2020-07-28 07:50 UTC, swaaz commented
my bad @ionicc 
![image](https://user-images.githubusercontent.com/42874695/88635317-28d6d200-d0d5-11ea-982d-a879859e4c26.png)

2020-07-30 12:06 UTC, swaaz commented
@ionicc bug fixed
![image](https://user-images.githubusercontent.com/42874695/88920871-32a23600-d28b-11ea-82b2-0d7893de4273.png)

2020-07-30 12:42 UTC, swaaz reviewed
bug fixed

2020-07-30 12:45 UTC, merged